# Site settings
course_name: Catequese em português em Cracóvia
course_description: | 
    Você está convidado(a) para participar da Catequese em português em Cracóvia, uma catequese presencial que acontecerá no Sanktuarium św. Jana Pawła II, venha estudar conosco os dogmas da fé católica, a celebração dos sacramentos e como viver conforme as leis de Deus!

course_description_2: | 
    A Catequese acontece aos sábados das 14h às 16h durante 8 sábados, confira a agenda abaixo.
    Teremos momentos de oração, partilha de experiências e estudo da Palavra de Deus. 

course_description_3: | 
    Se você deseja fortalecer a sua relação com Deus, aprender mais sobre a doutrina católica e se conectar com a comunidade, não perca essa oportunidade.
    Reserve essas datas em sua agenda e venha fazer parte da Catequese em português em Cracóvia.

course_description_4: |
    Esperamos por você!

course_semester: "Outono 2023"

baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://catequeseportuguespolonia.pl/" # the base hostname & protocol for your site

schoolname: "Catequese em português"
schoolurl: "https://catequeseportuguespolonia.pl"
# twitter_username: username 

address: |
    Sanktuarium św. Jana Pawła II
    32 Totus Tuus 30-610 Cracóvia
    Polônia

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%d/%m/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
