# Site settings
course_name: Catequese em português em Cracóvia
course_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ornare aliquam mattis. Donec hendrerit sollicitudin urna. Aliquam venenatis rutrum velit, at lobortis dui cursus a. Nam varius metus in turpis maximus, ut rhoncus tellus dictum. In aliquam tortor nec mi dapibus, sit amet vehicula dolor auctor."
course_semester: "Fall 1998"

baseurl: "/catequese-em-portugues-cracovia" # the subpath of your site, e.g. /blog/
url: "https://cassiodeveloper.com.br/" # the base hostname & protocol for your site

schoolname: "Hogwarts"
schoolurl: "https://hogwarts.edu"
twitter_username: username 

address: |
    Sanktuarium św. Jana Pawła II
    32 Totus Tuus 30-610 Cracóvia
    Polônia

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%d/%m/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
